### ISSUE TITLE
GSUB lookup needs to be corrected

### ISSUE THREAD

**Issue by starover77** [slavonic/fonts-znam#12]
When the Zanozhek (U+1CF55) is followed by the Kryzhik (U+1CF40), it should point to the composited form in the PUA. For the default (old style) form, it correctly pints to U+EA7B, but for SS02, it incorrectly points to the variant with the vertical omet (U+EA8D) instead of EADE. This should be an easy fix/

**Comment by typiconman** [comment]
Actually, I think I fixed this with 987934346164cef23f2e64a4b6da4f5f02a48306. Can you check with the current version of the font?

**Comment by starover77** [comment]
Sorry, it's still not working correctly. Normal usage works, but ss02 still produces the error.

**Comment by typiconman** [comment]
It works fine for me. Please double check.
![test](https://user-images.githubusercontent.com/5428695/53286380-aaa72b00-377e-11e9-8c3b-d5650acb261f.png)

**Comment by starover77** [comment]
It is working fine for me now. Thanks. Issue closed.
